/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RestaurantReviews__factory } from "./RestaurantReviews__factory";
export { YourContract__factory } from "./YourContract__factory";
